/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jonatino_natives_unix_unixc */

#ifndef _Included_com_github_jonatino_natives_unix_unixc
#define _Included_com_github_jonatino_natives_unix_unixc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jonatino_natives_unix_unixc
 * Method:    mem_read
 * Signature: (IJJI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jonatino_natives_unix_unixc_mem_1read__IJJI
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     com_github_jonatino_natives_unix_unixc
 * Method:    mem_write
 * Signature: (IJJI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jonatino_natives_unix_unixc_mem_1write__IJJI
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     com_github_jonatino_natives_unix_unixc
 * Method:    mem_read
 * Signature: (I[J[J[I)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jonatino_natives_unix_unixc_mem_1read__I_3J_3J_3I
  (JNIEnv *, jclass, jint, jlongArray, jlongArray, jintArray);

/*
 * Class:     com_github_jonatino_natives_unix_unixc
 * Method:    mem_write
 * Signature: (I[J[J[I)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jonatino_natives_unix_unixc_mem_1write__I_3J_3J_3I
  (JNIEnv *, jclass, jint, jlongArray, jlongArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
